Repository sovity/edc-ce, pull requests merged in 2023-01, with the labels that each got.

#4 chore: add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/epic_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: github

#6 Feat: pipeline publishes artifacts
  .github/workflows/gradle-publish.yml
Labels: enhancement, github

#11 feat: add ski aki extraction script
  README.md
  resources/docs/get_client.sh
Labels: enhancement

#13 chore: set dev as default environment (in docs and docker-compose)
  README.md
  resources/docs/docker-compose.yml
Labels: docker, documentation

#14 fix: connector not registering to broker due to null pointer exception
  extensions/catalog-transfer-extension/src/main/java/sender/RegisterConnectorRequestSender.java
Labels: bug

#16 Prepare release 1.0.1
  CHANGELOG.md
  gradle.properties
Labels: 🚀 Deploy

#17 Fix: uri to publish gradle artifacts
  build.gradle.kts
Labels: bug

#18 chore: update docker-compose to use correct registry
  resources/docs/docker-compose.yml
Labels: docker

#23 Feat: add connector description to broker message
  CHANGELOG.md
  extensions/catalog-transfer-extension/src/main/java/catalogtransfer/CatalogTransferExtension.java
  extensions/catalog-transfer-extension/src/main/java/sender/RegisterConnectorRequestSender.java
Labels: enhancement

#27 Create dependabot.yml
  .github/dependabot.yml
Labels: github

#35 Feat: add additional meta information to resourcec payload
  CHANGELOG.md
  README.md
  extensions/catalog-transfer-extension/src/main/java/sender/RegisterResourceRequestSender.java
  resources/docs/postman_collection.json
Labels: enhancement

#36 docs: update README to remove manual generation of SKI/AKI
  README.md
Labels: documentation

#43 docs: update README
  README.md
Labels: documentation

#57 feat: unregister connector on shutdown
  extensions/broker/src/main/java/de/sovity/extension/broker/BrokerExtension.java
  extensions/broker/src/main/java/de/sovity/extension/broker/sender/UnregisterConnectorRequestSender.java
  extensions/broker/src/main/java/de/sovity/extension/broker/sender/message/UnregisterConnectorMessage.java
  extensions/broker/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java
Labels: enhancement

#68 chore: add support for newer openssl versions to get_client script
  resources/docs/get_client.sh
Labels: bug
